
'use client';

/**
 * Professional Multilingual PDF Invoice Generator Service.
 * Optimized for O'zbek, Russian, and English.
 */

export interface InvoiceItem {
  name: string;
  quantity: number;
  unit: string;
  price: number;
}

export interface InvoiceData {
  title: string;
  type: 'in' | 'out';
  docNumber: string;
  date: string;
  partyName: string; 
  partyTypeLabel: string; 
  warehouseName: string;
  responsibleName: string;
  items: InvoiceItem[];
  currency: string;
  labels: {
    number: string;
    date: string;
    warehouse: string;
    product: string;
    qty: string;
    unit: string;
    price: string;
    total: string;
    grandTotal: string;
    shippedBy: string;
    receivedBy: string;
  };
}

export async function generateInvoicePDF(data: InvoiceData) {
  try {
    const jsPDFModule = await import("jspdf");
    const jsPDF = jsPDFModule.default;
    
    // Dynamically import jspdf-autotable to handle build environments
    const autoTableModule = await import("jspdf-autotable");
    const autoTable = autoTableModule.default || autoTableModule;
    
    const doc = new jsPDF({
      orientation: 'p',
      unit: 'mm',
      format: 'a4'
    });

    const themeColor = data.type === 'in' ? [59, 130, 246] : [225, 29, 72];

    // Design Header
    doc.setFillColor(themeColor[0], themeColor[1], themeColor[2]);
    doc.rect(0, 0, 210, 45, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold"); 
    doc.text(data.title.toUpperCase(), 15, 25);
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("omborchi.uz | Professional Warehouse Management", 15, 35);

    // Metadata Section
    doc.setTextColor(40, 40, 40);
    doc.setFontSize(10);
    
    // Grid alignment
    const col1 = 15;
    const col2 = 130;
    
    doc.setFont("helvetica", "bold");
    doc.text(`${data.partyTypeLabel}:`, col1, 60);
    doc.setFont("helvetica", "normal");
    doc.text(data.partyName || "N/A", col1, 66);

    doc.setFont("helvetica", "bold");
    doc.text(`${data.labels.warehouse}:`, col1, 78);
    doc.setFont("helvetica", "normal");
    doc.text(data.warehouseName || "N/A", col1, 84);
    
    doc.setFont("helvetica", "bold");
    doc.text(`${data.labels.number}:`, col2, 60);
    doc.setFont("helvetica", "normal");
    doc.text(data.docNumber || "---", col2, 66);

    doc.setFont("helvetica", "bold");
    doc.text(`${data.labels.date}:`, col2, 78);
    doc.setFont("helvetica", "normal");
    doc.text(data.date || "---", col2, 84);

    // Line separator
    doc.setDrawColor(200, 200, 200);
    doc.line(15, 92, 195, 92);

    // Table Data
    const tableRows = data.items.map((it, i) => [
      i + 1,
      it.name,
      it.quantity,
      it.unit,
      it.price.toLocaleString().replace(/,/g, ' '),
      (it.quantity * it.price).toLocaleString().replace(/,/g, ' ')
    ]);

    (doc as any).autoTable({
      startY: 100,
      head: [[
        '#',
        data.labels.product,
        data.labels.qty,
        data.labels.unit,
        data.labels.price,
        data.labels.total
      ]],
      body: tableRows,
      theme: 'striped',
      headStyles: {
        fillColor: themeColor,
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        halign: 'center',
        cellPadding: 4
      },
      styles: { fontSize: 9, font: 'helvetica', cellPadding: 3 },
      columnStyles: {
        0: { halign: 'center', cellWidth: 10 },
        2: { halign: 'center' },
        3: { halign: 'center' },
        4: { halign: 'right' },
        5: { halign: 'right' }
      }
    });

    // Summary
    const totalValue = data.items.reduce((sum, item) => sum + (item.quantity * item.price), 0);
    const finalY = (doc as any).lastAutoTable.finalY + 15;

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(themeColor[0], themeColor[1], themeColor[2]);
    doc.text(`${data.labels.grandTotal}: ${totalValue.toLocaleString().replace(/,/g, ' ')} ${data.currency}`, 195, finalY, { align: 'right' });

    // Footer Signatures
    const signY = Math.max(finalY + 35, 250);
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    
    doc.setFont("helvetica", "bold");
    doc.text(`${data.labels.shippedBy}: ________________`, 15, signY);
    doc.text(`${data.labels.receivedBy}: ________________`, 120, signY);

    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(`Doc ID: ${data.docNumber} | Generated by omborchi.uz System`, 105, 285, { align: 'center' });

    doc.save(`${data.title}_${data.docNumber}.pdf`);
  } catch (error) {
    console.error("PDF generation failed:", error);
  }
}
